services:
  backend:
    build: ./services/backend
    ports:
      - "3001:3001"
    expose:
      - 3001
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - SIGNATURES_DIR=${SIGNATURES_DIR}
    volumes:
      - ./services/backend/logs:/usr/src/app/logs
      - ./services/backend/uploads:/usr/src/app/uploads
    networks:
      - inventory_app
  db:
    build: 
      context: ./services/db
      dockerfile: Dockerfile
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
    networks:
      - inventory_app
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    # volumes:
    #   - ./services/frontend:/workspace
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    networks:
      - inventory_app
  nginx-inventory:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - inventory_app

volumes:
  postgres_data_prod:
  # static_volume:
  # uploads_volume:

networks:
  inventory_app:
    name: inventory_app
    driver: bridge