services:
  backend:
    build: ./services/backend
    container_name: inventory-backend
    ports:
      - "3001:3001"
    expose:
      - 3001
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - SIGNATURES_DIR=${SIGNATURES_DIR}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
    volumes:
      # - ./services/backend/node_modules:/usr/src/app/node_modules # TODO map
      - ./services/backend/logs:/usr/src/app/logs # TODO dont log all
      - ./services/backend/uploads:/usr/src/app/uploads
    restart: always
    networks:
      - inventory_network
      - nginx_network
      - db_network
  frontend:
    container_name: inventory-frontend
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - REACT_APP_SSO_GRAPH_API_ENDPOINT=${REACT_APP_SSO_GRAPH_API_ENDPOINT}
        - REACT_APP_SSO_REDIRECT_URI=${REACT_APP_SSO_REDIRECT_URI}
        - REACT_APP_SSO_TENANT_ID=${REACT_APP_SSO_TENANT_ID}
        - REACT_APP_SSO_CLIENT_ID=${REACT_APP_SSO_CLIENT_ID}
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    ports:
      - "3000:3000"
    # volumes:
    #   - ./services/frontend:/workspace
    restart: always
    networks:
      - nginx_network
      - inventory_network

volumes:
  postgres_data_prod:
  # static_volume:
  # uploads_volume:

networks:
  inventory_network:
    driver: bridge
  db_netowrk:
    external: true
  nginx_netowrk:
    external: true
