version: '3.8'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      # - static_volume:/home/app/web/project/static
      - uploads_volume:/home/app/web/project/uploads
      - ./services/web/logs:/home/app/web/project/logs
    expose: 
      - 5000
    env_file:
      - ./.env.prod
    environment:
      - LIVE=1
      - PYTHONUNBUFFER=1
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  react-dev:
    build: 
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    environment:
      - REACT_APP_API_BASE_URL=/api
  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.prod
    volumes:
      # - static_volume:/home/app/web/project/static
      - uploads_volume:/home/app/web/project/uploads
      - react_build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
      - react-dev

volumes:
  postgres_data_prod:
  static_volume:
  uploads_volume: