# Use an official MongoDB image
FROM mongo:latest

# Set the container's working directory
WORKDIR /usr/src/configs

# Copy your MongoDB scripts or configurations if any
# COPY ./my-mongo-configs .

# Expose port 27017 for MongoDB connections (default port)
EXPOSE 27017