export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


// ASSETS

export const ASSETS_FETCH_START = 'ASSETS_FETCH_START';
export const ASSETS_FETCH_SUCCESS = 'ASSET_FETCH_SUCCESS';
export const ASSETS_FETCH_FAIL = 'ASSET_FETCH_FAIL';

export const ASSET_CREATED = 'ASSET_CREATED';
export const ASSET_REGISTERED = 'ASSET_REGISTERED';
export const ASSET_CONDEMNED = 'ASSET_CONDEMNED';
export const ASSET_LOANED = 'ASSET_LOANED';
export const ASSET_RETURNED = 'ASSET_RETURNED';

export const ASSET_LOAD_START = 'ASSET_LOAD_START';
export const ASSET_LOAD_SUCCESS = 'ASSET_LOAD_SUCCESS';
export const ASSET_LOAD_FAIL = 'ASSET_LOAD_FAIL';
export const ASSET_BOOKMARK_TOGGLE = 'ASSET_BOOKMARK_CREATED';

export const ADD_ASSET_FILTERS = 'ADD_ASSET_FILTERS';
export const RESET_ASSET_FILTERS = 'RESET_ASSET_FILTERS';
export const UPDATE_ASSET_FILTERS = 'UPDATE_ASSET_FILTERS';

export const CLEAR_ASSETS_DATA = 'CLEAR_ASSETS_DATA';

// EVENTS

export const EVENTS_FETCH_START = 'EVENTS_FETCH_START';
export const EVENTS_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS';
export const EVENTS_FETCH_FAIL = 'EVENT_FETCH_FAIL';
export const EVENT_CREATED = 'EVENT_CREATED';

export const CLEAR_EVENTS_DATA = 'CLEAR_EVENTS_DATA';

// USERS

export const USERS_FETCH_START = 'USERS_FETCH_START';
export const USERS_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USERS_FETCH_FAIL = 'USER_FETCH_FAIL';

export const USER_CREATED = 'USER_CREATED';
export const USER_REMOVED = 'USER_REMOVED';
export const USER_LOANED = 'USER_LOANED';
export const USER_RETURNED = 'USER_RETURNED';

export const USER_LOAD_START = 'USER_LOAD_START';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
export const USER_BOOKMARK_TOGGLE = 'USER_BOOKMARK_CREATED';

export const ADD_USER_FILTERS = 'ADD_USER_FILTERS';
export const RESET_USER_FILTERS = 'RESET_USER_FILTERS';
export const UPDATE_USER_FILTERS = 'UPDATE_USER_FILTERS';

export const CLEAR_USERS_DATA = 'CLEAR_USERS_DATA';

// LOAN RETURN FORMS

export const SET_DETAILS = 'SET_DETAILS';
export const RESET_DETAILS = 'RESET_DETAILS';
export const PDF_OK = 'PDF_OK';

// SET PAGINATION

export const SET_PAGE = 'SET_PAGE';

// FORMS

export const FORM_SUBMIT_START = 'FORM_SUBMIT_START';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_FAIL = 'FORM_SUBMIT_FAIL';
export const CUSTOM_TOGGLE = 'CUSTOM_TOGGLE'
export const EXCEL_TOGGLE = 'EXCEL_TOGGLE';
export const SET_FORM_DETAILS = 'SET_FORM_DETAILS';

// UI

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_DRAWER_CONTENT = 'SET_DRAWER_CONTENT';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';


// DASHBOARD

export const DASHBOARD_FETCH_START = 'DASHBOARD_FETCH_START';
export const DASHBOARD_FETCH_SUCCESS = 'DASHBOARD_FETCH_SUCCESS';
export const DASHBOARD_FETCH_FAIL = 'DASHBOARD_FETCH_FAIL';